name: Deploy Blazor Server (OIDC Method)

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: '416610ff-917f-4695-ac86-dd9d52a0601d' 
          tenant-id: '754f9227-2c90-410d-8386-3023e1075d9e'
          subscription-id: 'b5cead49-bb71-4580-8722-db7cba388d62'

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish
        run: dotnet publish Restaurant_Website-main/restaurant-project/restaurant-project.csproj -c Release -o out

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Chanterelle-Italian'
          package: out